name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # build_and_test:
  #   name: Build and Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build
  #       run: cargo build --verbose
      
  #     - uses: actions/checkout@v3

  #     - name: Run tests
  #       run: cargo test --verbose
  
  dockerize:
    if: github.event_name != 'pull_request'
    name: Publish - Docker Hub
    # needs: [build_and_test]
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    # steps:
    #   - uses: actions/checkout@v3
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKER_USER }}
    #       password: ${{ secrets.DOCKER_TOKEN }}

    #   - name: Build Docker image
    #     run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      
    #   - name: Publish Docker image
    #     run: docker push $REPO
  
  redeploy:
    needs: [dockerize]
    runs-on: ubuntu-latest

    steps:
      - name: Call webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{}"
   
